[profile.default]
src = "src"
out = "out"
libs = ["lib"]

#[rpc_endpoints]
#gnosis = "${POLYGON_MUMBAI_RPC_URL}"
#morphTestnet = "${MORPH_RPC_URL}"
#
#[etherscan]
#arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "" }
#morphTestnet = { key = "${MORPH_ETHERSCAN_API_KEY}", url = "https://explorer-api-testnet.morphl2.io/api }

[doc]
title = 'MonuMints contracts'
